// teamTranslations.ts
export const teamTranslations: Record<string, string> = {

    // Premier League (20 clubs)
    'Arsenal': 'آرسنال',
    'Aston Villa': 'أستون فيلا',
    'AFC Bournemouth': 'بورنموث',
    'Brentford': 'برينتفورد',
    'Brighton & Hove Albion': 'برايتون أند هوف ألبیون',
    'Burnley': 'بيرنلي',
    'Chelsea': 'تشيلسي',
    'Crystal Palace': 'كريستال بالاس',
    'Everton': 'إيفرتون',
    'Fulham': 'فولهام',
    'Leeds United': 'ليدز يونايتد',
    'Liverpool': 'ليفربول',
    'Manchester City': 'مانشستر سيتي',
    'Manchester United': 'مانشستر يونايتد',
    'Newcastle United': 'نيوكاسل يونايتد',
    'Nottingham Forest': 'نوتنغهام فورست',
    'Sunderland': 'سندرلاند',
    'Tottenham Hotspur': 'توتنهام هوتسبير',
    'West Ham United': 'وست هام يونايتد',
    'Wolverhampton Wanderers': 'وولفرهامبتون واندررز',
  
    // La Liga (20 clubs)
    'Athletic Club': 'أتلتيك بلباو',
    'Alavés': 'ألافيس',
    'Barcelona': 'برشلونة',
    'Celta Vigo': 'سيلتا فيغو',
    'Elche': 'إلتشي',
    'Espanyol': 'إسبانيول',
    'Valencia': 'فالنسيا',
    'Atlético de Madrid': 'أتلتيكو مدريد',
    'Getafe': 'خيتافي',
    'Rayo Vallecano': 'رايو فاليكانو',
    'Real Madrid': 'ريال مدريد',
    'Sevilla': 'إشبيلية',
    'Real Betis': 'ريال بيتيس',
    'Villarreal': 'فياريال',
    'Real Sociedad': 'ريال سوسيداد',
    'Osasuna': 'أوساسونا',
    'RCD Mallorca': 'ريال نادي مايوركا',
    'Cádiz': 'قادش',
    'Granada': 'غرناطة',
    'Valladolid': 'بلد الوليد',
  
    // Serie A (20 clubs)
    'Juventus': 'يوفنتوس',
    'Inter Milan': 'إنتر ميلان',
    'AC Milan': 'إيه سي ميلان',
    'Roma': 'روما',
    'Napoli': 'نابولي',
    'Atalanta': 'أتالانتا',
    'Lazio': 'لاتسيو',
    'Torino': 'تورينو',
    'Fiorentina': 'فيورنتينا',
    'Bologna': 'بولونيا',
    'Sassuolo': 'ساسولو',
    'Frosinone': 'فروسينوني',
    'Empoli': 'إمبولي',
    'Genoa': 'جينوا',
    'Udinese': 'أودينيزي',
    'Monza': 'مونزا',
    'Lecce': 'ليتشي',
    'Spezia': 'سبزيا',
    'Verona': 'هيلاس فيرونا',
    'Salernitana': 'ساليرنيتانا',
  
    // Bundesliga (18 clubs)
    'Bayern Munich': 'بايرن ميونخ',
    'Borussia Dortmund': 'بوروسيا دورتموند',
    'Eintracht Frankfurt': 'آينتراخت فرانكفورت',
    'Bayer Leverkusen': 'باير ليفركوزن',
    'RB Leipzig': 'لايبزيغ',
    'VfL Wolfsburg': 'فولفسبورغ',
    'Stuttgart': 'شتوتغارت',
    'Union Berlin': 'أونيون برلين',
    'Werder Bremen': 'وردر بريمن',
    'Mainz': 'ماينز',
    'Hoffenheim': 'هوفنهايم',
    'Heidenheim': 'هايدنهايم',
    'Freiburg': 'فرايبورغ',
    'Dortmund': 'دورتموند',
    'Koln': 'كولن',
    'Bochum': 'بوخوم',
    'Augsburg': 'أوجسبورغ',
    'Hansa Rostock': 'هانزا روستوك',
  
    // Ligue 1 (18 clubs)
    'Paris Saint-Germain': 'باريس سان جيرمان',
    'Marseille': 'مرسيليا',
    'Monaco': 'موناكو',
    'Lyon': 'ليون',
    'Lens': 'لنس',
    'Lille': 'ليل',
    'Rennes': 'رين',
    'Strasbourg': 'ستراسبورغ',
    'Brest': 'بريست',
    'Nice': 'نيس',
    'Toulouse': 'تولوز',
    'Angers': 'أنجيه',
    'Auxerre': 'أوكسير',
    'Le Havre': 'لوهافر',
    'Nantes': 'نانت',
    'Metz': 'ميتز',
    'Lorient': 'لورين',
    'Clermont': 'كليرمون',
  
    // Botola Pro (16 clubs)
    'Wydad Casablanca': 'الوداد الرياضي',
    'Raja Casablanca': 'الرجاء الرياضي',
    'FAR Rabat': 'الجيش الملكي',
    'Moghreb Tétouan': 'المغرب التطواني',
    'Olympic Safi': 'أولمبيك آسفي',
    'Hassania Agadir': 'حسنية أكادير',
    'Ittihad Tanger': 'اتحاد طنجة',
    'Difaa El Jadida': 'الدفاع الحسني الجديدي',
    'RS Berkane': 'الرجاء الرياضي البركاني',
    'Olympic Khouribga': 'أولمبيك خريبكة',
    'Youssoufia Berrechid': 'اليوسفية البرشيد',
    'Mouloudia Oujda': 'المولودية الوجدية',
    'Renaissance Berkane': 'نهضة بركان',
    'Chabab Mohammédia': 'شباب المحمدية',
    'Kawkab Marrakech': 'الكوكب المراكشي',
    'Racing de Casablanca': 'الرجاء البيضاوي',
  
    // UEFA Champions League 2025-26 (phase de poules, 36 clubs) :contentReference[oaicite:0]{index=0}
    'PSV Eindhoven': 'بي إس في آيندهوفن',
    'Ajax': 'أياكس',
    'Sporting CP': 'سبورتينغ لشبونة',
    'Olympiacos': 'أولمبياكوس',
    'Benfica': 'بنفيكا',
    'Club Brugge': 'كلوب بروج',
    'Copenhagen': 'كوبنهاغن',
    'Galatasaray': 'غلطة سراي',
    'Union Saint-Gilloise': 'يونيون سان جيلوّيز',
    'Qarabağ': 'قره باغ',
    'Pafos': 'بابوس',
    'Kairat Almaty': 'كايارت ألماتي',
  
  };
  
  export const getTeamTranslation = (teamName: string): string => {
    return teamTranslations[teamName] || teamName;
  };
  