// Static mapping for known team names to Arabic equivalents
// Extend this list as needed.
export const teamTranslations: Record<string, string> = {
  // Premier League Teams
  'Manchester City': 'مانشستر سيتي',
  'Arsenal': 'أرسنال',
  'Liverpool': 'ليفربول',
  'Chelsea': 'تشيلسي',
  'Manchester United': 'مانشستر يونايتد',
  'Tottenham': 'توتنهام',
  'Newcastle': 'نيوكاسل',
  'Brighton': 'برايتون',
  'West Ham': 'وست هام',
  'Aston Villa': 'أستون فيلا',
  'Crystal Palace': 'كريستال بالاس',
  'Fulham': 'فولهام',
  'Brentford': 'برينتفورد',
  'Wolves': 'وولفرهامبتون',
  'Everton': 'إيفرتون',
  'Leicester': 'ليستر سيتي',
  'Leeds United': 'ليدز يونايتد',
  'Burnley': 'بيرنلي',
  'Southampton': 'ساوثهامبتون',
  'Watford': 'واتفورد',
  'Norwich': 'نورويتش سيتي',
  'Sheffield United': 'شيفيلد يونايتد',
  'Bournemouth': 'بورنموث',
  'Nottingham Forest': 'نوتينغهام فوريست',

  // La Liga Teams
  'Real Madrid': 'ريال مدريد',
  'Barcelona': 'برشلونة',
  'Atletico Madrid': 'أتلتيكو مدريد',
  'Real Sociedad': 'ريال سوسيداد',
  'Villarreal': 'فياريال',
  'Sevilla': 'إشبيلية',
  'Real Betis': 'ريال بيتيس',
  'Valencia': 'فالنسيا',
  'Athletic Bilbao': 'أتلتيك بيلباو',
  'Celta Vigo': 'سيلتا فيغو',
  'Espanyol': 'إسبانيول',
  'Getafe': 'خيتافي',
  'Granada': 'غرناطة',
  'Levante': 'ليفانتي',
  'Mallorca': 'مايوركا',
  'Osasuna': 'أوساسونا',
  'Rayo Vallecano': 'رايو فاليكانو',
  'Real Valladolid': 'ريال بايادوليد',
  'Alaves': 'ألافيس',
  'Cadiz': 'قادش',
  'Elche': 'إلتشي',

  // Serie A Teams
  'Juventus': 'يوفنتوس',
  'Inter Milan': 'إنتر ميلان',
  'AC Milan': 'ميلان',
  'Napoli': 'نابولي',
  'Roma': 'روما',
  'Lazio': 'لاتسيو',
  'Atalanta': 'أتالانتا',
  'Fiorentina': 'فيورنتينا',
  'Torino': 'تورينو',
  'Sassuolo': 'ساسولو',
  'Udinese': 'أودينيزي',
  'Bologna': 'بولونيا',
  'Sampdoria': 'سامبدوريا',
  'Hellas Verona': 'هيلاس فيرونا',
  'Spezia': 'سبيتزيا',
  'Cagliari': 'كالياري',
  'Genoa': 'جنوة',
  'Empoli': 'إمبولي',
  'Venezia': 'فينيسيا',
  'Salernitana': 'ساليرنيتانا',
  'Monza': 'مونزا',
  'Cremonese': 'كريمونيزي',
  'Lecce': 'ليتشي',

  // Bundesliga Teams
  'Bayern Munich': 'بايرن ميونخ',
  'Borussia Dortmund': 'بوروسيا دورتموند',
  'RB Leipzig': 'آر بي لايبزيغ',
  'Bayer Leverkusen': 'باير ليفركوزن',
  'Eintracht Frankfurt': 'آينتراخت فرانكفورت',
  'Borussia Monchengladbach': 'بوروسيا مونشنغلادباخ',
  'Union Berlin': 'يونيون برلين',
  'SC Freiburg': 'فرايبورغ',
  'FC Koln': 'كولن',
  'Mainz': 'ماينز',
  'Hoffenheim': 'هوفنهايم',
  'VfL Wolfsburg': 'فولفسبورغ',
  'Hertha Berlin': 'هيرتا برلين',
  'VfB Stuttgart': 'شتوتغارت',
  'Augsburg': 'أوغسبورغ',
  'Arminia Bielefeld': 'أرمينيا بيليفيلد',
  'Greuther Furth': 'غرويتر فورت',
  'Werder Bremen': 'فيردر بريمن',

  // Ligue 1 Teams
  'Paris Saint-Germain': 'باريس سان جيرمان',
  'Marseille': 'مارسيليا',
  'Lyon': 'ليون',
  'Monaco': 'موناكو',
  'Lille': 'ليل',
  'Nice': 'نيس',
  'Rennes': 'رين',
  'Strasbourg': 'ستراسبورغ',
  'Montpellier': 'مونبلييه',
  'Nantes': 'نانت',
  'Reims': 'ريمس',
  'Lens': 'لانس',
  'Brest': 'بريست',
  'Angers': 'أنجيه',
  'Clermont': 'كليرمون',
  'Lorient': 'لوريان',
  'Troyes': 'تروا',
  'Saint-Etienne': 'سان إتيان',
  'Bordeaux': 'بوردو',
  'Metz': 'ميتز',

  // Champions League Teams (additional)
  'Manchester City FC': 'مانشستر سيتي',
  'Real Madrid CF': 'ريال مدريد',
  'FC Barcelona': 'برشلونة',
  'Liverpool FC': 'ليفربول',
  'Chelsea FC': 'تشيلسي',
  'Bayern München': 'بايرن ميونخ',
  'Paris Saint Germain': 'باريس سان جيرمان',
  'Juventus FC': 'يوفنتوس',
  'Inter': 'إنتر ميلان',
  'Milan': 'ميلان',
  'Atletico de Madrid': 'أتلتيكو مدريد',
};

export function getArabicTeamName(teamName: string): string {
  // If already contains Arabic characters, return as-is
  if (/[\u0600-\u06FF]/.test(teamName)) return teamName;
  return teamTranslations[teamName] || teamName;
}
