name: Scrape YSScores Transfers

on:
  schedule:
    - cron: '0 6 * * *' # daily at 06:00 UTC
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run scraper
        run: npm run scrape:ysscores

      - name: Commit scraped output
        run: |
          git config user.name "github-actions[bot]";
          git config user.email "github-actions[bot]@users.noreply.github.com";
          git add public/scraped-transfers.json public/scraped-transfers.html || true;
          git commit -m "chore(scraper): update scraped transfers" || echo "no changes to commit";
          git push origin HEAD:main || echo "push failed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
